name: CI/CD Iris MLOps

on:
  push:
    branches: [ main ]

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt dvc[all] mlflow dagshub joblib

      - name: Configure DVC remote
        run: |
          dvc remote modify origin auth basic
          dvc remote modify origin user ${{ secrets.DAGSHUB_USERNAME }}
          dvc remote modify origin password ${{ secrets.DAGSHUB_TOKEN }}

      - name: Pull dataset from DagsHub
        run: dvc pull data/iris.csv

      - name: Train model and log with MLflow
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/santosh.flyingmachine/iris_dagshub_docker.mlflow
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: python train.py

      - name: Commit updated model with DVC
        run: |
            dvc commit -f models/model.pkl
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add dvc.lock
            git commit -m "Update model version from CI run" || echo "No changes to commit"

      - name: Push model to DagsHub storage
        run: dvc push

      - name: Push metadata to GitHub
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t value:latest .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
            docker build -t ghcr.io/${{ github.repository }}:latest .
            docker push ghcr.io/${{ github.repository }}:latest
 